### ISSUE TITLE
InvariantViolation : requireNativeComponent RNCViewpager was not found in the UI manager

### ISSUE THREAD

**Issue by sharief-edv** [react-native-community/react-native-viewpager#18] opened 2019-03-18 09:52 UTC
![image](https://user-images.githubusercontent.com/36036378/54521761-962b0c80-4991-11e9-96c9-34fa79518aa1.png)

**Comment by ferrannp** [comment] 2019-03-18 11:04
It looks like you did not run `react-native link @react-native-community/viewpager` ?

**Comment by sharief-edv** [comment] 2019-03-18 15:58
I do run that , But the mistake i have done before was **_(I DID NOT MENTION IT FIRST )_** , i didn't  run yarn add **@react-native-community/viewpager** at first  instead i have ran the _npm install --save  @react-native-community/viewpager_  as i thought i have to do npm not  yarn .  After i realized and ran yarn command  followed by link command , i am getting the same error.

**Comment by ferrannp** [comment] 2019-03-18 16:01
Is the `example` in this repository working for you?

**Comment by sharief-edv** [comment] 2019-03-18 17:09
No @ferrannp , I am getting error

**Comment by SSWeedie** [comment] 2019-04-18 05:53
I am also getting this error, so what is the solution ?

**Comment by ferrannp** [comment] 2019-04-18 14:46
What about not linking / using it in iOS for now? It is not implemented on iOS anyway.

**Comment by SSWeedie** [comment] 2019-04-20 08:31
Still get the same error without linking

**Comment by ferrannp** [comment] 2019-04-30 09:46
@SSWeedie can I see some code? You should only link it on Android but specially on JS, you should only require it for Android.

**Comment by renishdeveloper** [comment] 2019-04-30 10:48
Getting the same error
Invariant Violation: Invariant Violation:
requireNativeComponent : "RNCViewPager" was not found in the UIManager".

I run both the commands
1.     For installation
        npm install @react-native-community/viewpager
2.     For linking the library
        react-native link @react-native-community/viewpager


System configuration : 
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS 
      CPU: (6) x64 AMD FX(tm)-6300 Six-Core Processor
      Memory: 920.17 MB / 3.59 GB
      
    Binaries:
      Node: 8.16.0
      npm: 6.4.1
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by ferrannp** [comment] 2019-04-30 12:02
Can someone post a repo where this can be reproduced?

**Comment by renishdeveloper** [comment] 2019-05-06 09:30
@ferrannp Here is the complete code with the implementation steps :

For installation
npm install @react-native-community/viewpager

For linking the library
 react-native link @react-native-community/viewpager

Not followed the manual steps as the react-native link @react-native-community/viewpager command does it for me.

Import view pager
import ViewPager from "@react-native-community/viewpager";

ViewPager component

  <ViewPager
            style={styles.viewPager}
            initialPage={0}>
            <View key="1">
              <Text>First page</Text>
            </View>
            <View key="2">
              <Text>Second page</Text>
            </View>
          </ViewPager>

>

**Comment by AppUU** [comment] 2019-05-10 09:54
Add the RNCViewPagerPackage class to your list of exported packages.

**Comment by ferrannp** [comment] 2019-05-10 12:08
@renishdeveloper that works for me. Do you have a repository I can try?

**Comment by sangyakhare** [comment] 2019-06-04 20:05
![image](https://user-images.githubusercontent.com/49403660/58910059-a1651d00-86e2-11e9-9b5c-d759fe65de16.png)


And its on Android
Same error here. I am also struggling with a similar error stating RNCWebview not found in UIManager for WebView as well for Android. Its very frustrating.

**Comment by AA25** [comment] 2019-06-07 18:46
I don't know if this is useful or not, but I was also getting this issue with a fresh new project. I tried manually linking but that didn't seem to fix the problem. Again, since it was a new project I decided to delete the project and tried again. But this time adding and linking viewpager before running the app on android and creating a component making use of viewpager. It works now thankfully though I'm not fully sure why

**Comment by ptrocki** [comment] 2019-06-10 16:42
I checked examples and work. I also tested a fresh project and  I ran below commands
```
mkdir toDelete
cd toDelete/
react-native init AwesomeProjectToDelete
cd AwesomeProjectToDelete/
yarn 
yarn add @react-native-community/viewpager
react-native link @react-native-community/viewpager
react-native run-ios
react-native run-android
```
Both commands `react-native run-ios` and `react-native run-android` work with no errors. 
My configuration:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 1.74 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
```
Did you linked this lib manually or used above commands ? 
@AA25 
If you want to link lib manually, checkout example dir.

**Comment by DanielVenturini** [comment] 2019-06-23 17:01
I've linked the `react-native-viewpager` using the command in Android, but it doesn't link in following file:

`android/app/src/main/.../MainApplication.java`

After I linked manually, it works for me.

For full manually link:
https://github.com/react-native-community/react-native-viewpager/blob/master/README.md#android

**Comment by DrobyshevAlex** [comment] 2019-08-19 09:42
How i can use https://github.com/react-native-community/react-native-viewpager/blob/master/README.md#android
if i use expo? I have't 'android' folder

**Comment by ferrannp** [comment] 2019-09-01 12:05
@DrobyshevAlex you cannot as this library is not supported by Expo. You would have to eject your project.

I am closing this issue as there is no reproducible repro and it is working fine for me in the `example` and in a new project created with `react-native init.

**Closed by ferrannp** 2019-09-01 12:05 UTC
Labels: Resolution: Needs Repro

**Comment by jaythakkar2807** [comment] 2019-10-09 07:14
@ferrannp, I have installed "yarn add @react-native-community/viewpager" and then follow the steps but It not run in expo.

**Comment by yzalvov** [comment] 2019-11-24 14:01
> @DrobyshevAlex you cannot as this library is not supported by Expo. You would have to eject your project.

The interesting thing is that Expo people recommend using the `react-native-viewpager` instead of one of their deprecated interface. It is literally the first-line link on the [ViewPagerAndroid](https://docs.expo.io/versions/v35.0.0/react-native/viewpagerandroid/) page.

**Comment by aryojamousi** [comment] 2019-12-02 12:59
I am on RN 61.5 with `"@react-native-community/viewpager": "^3.1.0"` and got crashes on iOS (not Android) with the said error. 
What helped was manually linking the dependancy for iOS:
put
```
  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'
```
in your `Podfile` and run `cd ios && pod install`

**Comment by sushrut-desora** [comment] 2020-02-13 16:59
I had the same issue using react-native 0.61.4 and "@react-native-community/viewpager": "^3.3.0" on android. It  was resolved after doing ```react-native link @react-native-community/viewpager```. Why do i have to link it when react native uses auto linking ?

**Comment by DatNguyenWoft** [comment] 2020-04-05 09:21
i have used library react-native-scrollable-tab-view version 1.0.0, it has dependency @react-native-community/viewpager then error ocurce. But when i downgrade to version 0.10.0 this error is gone.

**Comment by brentvatne** [comment] 2020-05-16 20:52
if you're using expo and you have this issue make sure you're on sdk-37 and see this docs page for installation instructions https://docs.expo.io/versions/latest/sdk/view-pager/

**Comment by brentvatne** [comment] 2020-05-16 20:54
@yzalvov - we only release sdks once per quarter, so all you need is for someone to make a change in one of the react-native-community repos one day after that release and then there is nothing we can do until the next release. so that is why you would have seen different recommendations in the docs. w

**Comment by troZee** [comment] 2020-05-19 12:13
I checked, if autolinking issue exist and I can't reproduce it. You check it on my branch here: 
https://github.com/troZee/viewPagerExample/tree/autolinking

**Comment by troZee** [comment] 2020-05-19 12:21
I checked and autolinking for 0.62 here:
https://github.com/troZee/viewPagerExample/tree/autolinking

And everything works fine.

**Comment by brambang** [comment] 2020-06-05 15:56
i had same issue, is it maybe the problem is only for expokit app (eject from manage workflow).
Because my apps didnt get any autolinking, include viewpager

**Comment by Niz47** [comment] 2020-08-11 20:16
> Getting the same error
> Invariant Violation: Invariant Violation:
> requireNativeComponent : "RNCViewPager" was not found in the UIManager".
> 
> I run both the commands
> 
>     1. ```
>        For installation
>         npm install @react-native-community/viewpager
>        ```
> 
>     2. ```
>        For linking the library
>         react-native link @react-native-community/viewpager
>        ```
> 
> 
> System configuration :
> System:
> OS: Linux 4.15 Ubuntu 18.04.2 LTS
> CPU: (6) x64 AMD FX(tm)-6300 Six-Core Processor
> Memory: 920.17 MB / 3.59 GB
> 
> ```
> Binaries:
>   Node: 8.16.0
>   npm: 6.4.1
> npmPackages:
>   react: 16.8.3 => 16.8.3 
>   react-native: 0.59.5 => 0.59.5 
> npmGlobalPackages:
>   react-native-cli: 2.0.1
> ```

saved my time :) thanks a million

**Comment by sushrut-desora** [comment] 2020-08-12 14:28
> i had same issue, is it maybe the problem is only for expokit app (eject from manage workflow).
> Because my apps didnt get any autolinking, include viewpager

It might be related to this issue. https://github.com/expo/expo-cli/issues/1398

**Comment by narek11** [comment] 2021-04-23 10:30
To make it work on ios I had to do `react-native link react-native-pager-view` then `cd ios; pod install; cd ..`
